name: zellij
version: 0.43.0
summary: A terminal workspace
description: |
  Zellij is a terminal workspace that aims to be a multi-purpose and flexible
  terminal environment.
confinement: classic
base: core24
website: https://zellij.dev
issues: https://github.com/zellij-org/zellij/issues
source-code: https://github.com/dominz88/zellij-snap
contact: dominguez.lopez.luis.alonso@laposte.net

platforms:
  amd64:
  arm64:

parts:
  zellij:
    source: https://github.com/zellij-org/zellij.git
    source-tag: "v$SNAPCRAFT_PROJECT_VERSION"
    plugin: rust

apps:
  zellij:
    command: bin/zellij
