name: zellij
version: 0.40.1
summary: A terminal workspace
description: |
  Zellij is a terminal workspace that aims to be a multi-purpose and flexible
  terminal environment.
confinement: classic
base: core22
website: https://zellij.dev
source-code: https://github.com/dominz88/zellij-snap
issues: https://github.com/zellij-org/zellij/issues

architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64
  
parts:
  zellij:
    source: https://github.com/zellij-org/zellij.git
    source-tag: v0.40.1
    plugin: rust

  rust-deps:
    plugin: nil
    build-packages:
      - rustc
      - cargo

apps:
  zellij:
    command: bin/zellij
