name: zellij
version: 0.42.1
summary: A terminal workspace
description: |
  Zellij is a terminal workspace that aims to be a multi-purpose and flexible
  terminal environment.
confinement: classic
base: core22
website: https://zellij.dev
issues: https://github.com/zellij-org/zellij/issues
source-code: https://github.com/dominz88/zellij-snap
contact: dominguez.lopez.luis.alonso@laposte.net

architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64
  
parts:
  zellij:
    source: https://github.com/zellij-org/zellij.git
    source-tag: v0.42.1
    plugin: rust
    override-build: |
      snapcraftctl build
      ARCH=$(dpkg --print-architecture)
      if [ "$ARCH" = "arm64" ]; then
        patchelf --set-interpreter /snap/core22/current/lib/ld-linux-aarch64.so.1 bin/zellij
        patchelf --set-rpath /snap/core22/current/lib/aarch64-linux-gnu bin/zellij
      elif [ "$ARCH" = "amd64" ]; then
        patchelf --set-interpreter /snap/core22/current/lib64/ld-linux-x86-64.so.2 bin/zellij
        patchelf --set-rpath /snap/core22/current/lib/x86_64-linux-gnu bin/zellij
      fi

  rust-deps:
    plugin: nil
    build-packages:
      - rustc
      - cargo

apps:
  zellij:
    command: bin/zellij
